image: stronglytyped/arm-none-eabi-gcc

pipelines:
  default:
    - step:
        name: 'test'
        script:
          - apt-get install -y python3 python3-pip idle3
          - pip install -r common/requirements.txt
          - make
        
