image: addis0n/arm-none-eabi-gcc-plus-python:cppcheck

pipelines:
  default:
    - step:
        name: 'Build all firmware code'
        script:
          - pip install -r common/requirements.txt
          - make
          - cppcheck --version
        
    - step:
        name: 'Run the linter'
        script:
          - make lint