image: atlassian/default-image:3

pipelines:
  default:
    - step:
        image: python:3 
        name: 'test'
        script:
          - pip install -r common/requirements.txt
          - make
        
