image: addis0n/arm-none-eabi-gcc-plus-python:wfe2022

pipelines:
  default:
    - step:
        name: 'Build all firmware code'
        script:
          - pip install -r common/requirements.txt
          - make
        
