image: stronglytyped/arm-none-eabi-gcc

pipelines:
  default:
    - step:
        image: python:3 
        name: 'Install python dependencies'
        script:
          - pip install -r common/requirements.txt
    - step:
        script: 
          - make
        
