name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: addis0n/arm-none-eabi-gcc-plus-python:wfe2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r common/requirements.txt

      - name: Build all firmware code
        run: make all
